### PR TITLE
Feature / Store in subdirectory of userData

### PR DESCRIPTION
**Pull request by slabruyere**
**Description**
First draft to allow storage in subdirectory of userData, as mentionned in [Issue#28](https://github.com/jviotti/electron-json-storage/issues/2)
It might not be a perfect approach and I would be glad to discuss implementation with the contributors.

**Links**
https://github.com/jviotti/electron-json-storage/issues/28

### CODE REVIEW

**Comment by jviotti** [comment]
How about having a top level static property defining the subdirectory name (with a sane default, like `settings`), and having the `.set()` function create it only if necessary?

Usage would look something like this:

```js
const storage = require('electron-json-storage');

// Set a custom namespace, otherwise `storage.namespace === 'settings'`
storage.namespace = 'new-namespace-directory';

// This creates `new-namspace-directory/foo.json` in the user data path.
storage.set('foo', { hello: 'world' }, (error) => console.error(error));
```

The core logic of this PR gets simplified and moved to `.set()` .

What do you think?

**Comment by slabruyere** [comment]
Hi Juan,

Sorry for the late reply :)

I totally agree on the need for a sane default value!

To set the namespace directory, I personally prefer calling a method right after the `require` statement to make sure I won't have to worry about it later rather than setting the value the way you suggest, but I guess that's a matter of personal taste.

Best,

**Comment by jviotti** [comment]
Hi @slabruyere ,

> To set the namespace directory, I personally prefer calling a method right after the require statement to make sure I won't have to worry about it later rather than setting the value the way you suggest, but I guess that's a matter of personal taste.

A setter and getter sound fine to me as well, up to you!

**Comment by jviotti** [comment]
Closing in favor of https://github.com/jviotti/electron-json-storage/pull/43. Thanks a lot!

**Pull request closed without merging**
