### PR TITLE
Resolving "Callback has already been called" issue

### PR DESCRIPTION
**Pull request by nab911**
Removed callback from try block and return if the catch block is entered.
This resolves and issue when the callback function throws and error and results in
the error "Callback has already been called".

@jviotti

### CODE REVIEW

**Comment by nab911** [comment]
Sure thing! I'll try and get something in today.

**Comment by nab911** [comment]
So I kept trying to write a test that would demonstrate the behavior but the fix properly fixed it. Now, if the callback that is passed in throws an error, that error will be properly reported instead of "Callback has already been called".  @jviotti

**Comment by jviotti** [comment]
That's perfect! A test case that failed before your patch and now passes is exactly what we need!

**Comment by nab911** [comment]
I tried for another hour but given the async nature of the functions, I was not able to write a test that tested anything useful. If you want to give it a shot, this code block:
`storage.get('foo', function(error, data) {         
     throw "Foo Error";         
 });`
Before it would throw Error: Callback has already been called, now it will properly throw Error: Foo Error.
I just couldn't get mocha to play nicely and catch the async error.

**Comment by jviotti** [comment]
Hey there! No worries, let me give it a shot myself!

**Comment by jviotti** [comment]
This is very difficult to capture in a test case indeed :/ I'll merge it as it is in this case. Thank you very much!

**Comment by jviotti** [comment]
I've published v2.0.2 to npm.

**Pull request merged**
