### PR TITLE
When callbacks are provided, do not return promises as well

### LINKED ISSUE #5: Does not work using remote
Two issues were found with this working as remote

First with promises:

See https://github.com/atom/electron/issues/3740

An application using this as remote will hang.  This can be resolved by removing the returns from the various exported methods, and using the callback.

Second, the app lookup in utils.js fails - the app needs to be retrieved from the electron remote instead of directly from electron.

### PR DESCRIPTION
**Pull request by jseriff**
Fixes #5 

Consumers of this electorn-json-storage can either use the promises that are returned, or provide a callback, which results in no return.

### CODE REVIEW

**Comment by jviotti** [comment]
Thanks a lot for the pull request. As commented in the original issue, I say lets get rid of Bluebird completely and only support callbacks, and let the user promisify if he wants to.

**Comment by jseriff** [comment]
That sounds fine with me.  I have closed this PR.

**Comment by jviotti** [comment]
@jseriff Do you want to work on this yourself? Let me know, so we don't work on the same thing separately :)

**Comment by jseriff** [comment]
@jviotti I'm not working on it immediately, go for it.

**Pull request closed without merging**
